social_news_site/social_news_site/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from . import settings
from articles.views import page_not_found


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('articles.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

social_news_site/users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('register_done/', views.RegisterDoneView.as_view(), name='register_done'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
]

social_news_site/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    photo = models.ImageField(upload_to="photos/users/", blank=True, null=True)
    message_count = models.IntegerField(default=0)


social_news_site/users/forms.py
from re import match, search
from typing import Any
from django import forms
from django.forms import FileInput
from django.contrib.auth import get_user_model
from django.http import JsonResponse

class LoginForm(forms.ModelForm):
    username = forms.CharField(label='',
        widget=forms.TextInput(attrs={
            'class': 'form__input small',
            'placeholder': 'Логин',
        }))
    
    password = forms.CharField(label='',
        widget=forms.PasswordInput(attrs={
            'class': 'form__input small',
            'placeholder': 'Пароль',
        }))
    
    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegisterForm(forms.ModelForm):
    username = forms.CharField(label='',
        widget=forms.TextInput(attrs={
            'class': 'form__input username',
            'placeholder': 'Логин',
            'maxlength': '150',
        }))
    password = forms.CharField(label='',
        widget=forms.PasswordInput(attrs={
            'class': 'form__input password password',
            'placeholder': 'Пароль',
            'maxlength': '128',
        }))
    password2 = forms.CharField(label='',
        widget=forms.PasswordInput(attrs={
            'class': 'form__input',
            'placeholder': 'Повтор пароля',
            'maxlength': '128',
        }))
    
    
    class Meta:
        model = get_user_model()
        fields = ['username', 'password', 'password2']
        
    
    def clean_password(self):
        cd = self.cleaned_data
        if not (search(r'[a-z]', cd['password']) and search(r'[0-9]', cd['password'])):
            self.add_error('password', 'Пароль должен содержать латинские буквы, цифры и не менее 8 символов')
        else:
            return cd['password']
    
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            self.add_error('password', 'Пароли не совпадают')
        return cd['password2']

    def clean_username(self):
        username = self.cleaned_data['username']
        if not bool(match(r'[a-zA-Z0-9]{4,}$', username)):
            self.add_error('username', 'Логин должен содержать латинские буквы или цифры и не менее 4 символов')
        elif get_user_model().objects.filter(username=username).exists():
            self.add_error('username', 'Пользователь с таким логином уже существует')
        return username



class ProfileEditForm(forms.ModelForm):
    photo = forms.ImageField(label='', widget=FileInput)
    
    class Meta:
        model = get_user_model()
        fields = ['photo']

social_news_site/users/views.py
from django.urls import reverse_lazy
from django.views import View
from django.http import JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect, render
from .forms import LoginForm, RegisterForm, ProfileEditForm
from django.views.generic import UpdateView
from django.contrib.auth import get_user_model
from social_news_site.settings import DEFAULT_USER_IMAGE
from articles.models import Articles
from django.db.models import Count
from django.core.paginator import Paginator
from articles.views import forbidden_page

class LoginView(View):
    
    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        if username and password:
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return JsonResponse({}, status=201)
            return JsonResponse(data={'detail': 'Не верный логин или пароль'}, status=400)
        return JsonResponse(data={'detail': 'Введите логин пароль'}, status=400)


class LogoutView(View):
    def post(self, request):
        logout(request)
        return redirect('index')


class RegisterView(View):
    
    def post(self, request):
        form = RegisterForm(request.POST)
        print(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            
            return JsonResponse(data={}, status=201)
        return JsonResponse(data=form.errors, status=400)


class RegisterDoneView(View):
    
    def get(self, request):
        
        context = {
            'LoginForm': LoginForm(),
            'RegisterForm': RegisterForm(),
        }
        
        return render(request, 'users/register_done.html', context)    


class ProfileView(UpdateView):
    
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return forbidden_page(request)
        return super(ProfileView, self).dispatch(request, *args, **kwargs)
    
    model = get_user_model()
    template_name = 'users/profile.html'
    form_class = ProfileEditForm
    extra_context = {
        'title': 'Профиль',
        'default_photo': DEFAULT_USER_IMAGE,
    }
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        themes = Articles.objects.filter(author=self.request.user).annotate(count=Count("articlescontent__pk")-1)
        paginator = Paginator(themes, 4)
        page_number = self.request.GET.get('page', 1)
        themes = paginator.get_page(page_number)
        context['themes'] = themes
        return context

    
    def get_success_url(self):
        return reverse_lazy('profile')
    
    def get_object(self, queryset=None):
        return self.request.user

social_news_site/users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=1200">
    <link rel="stylesheet" href="{% static 'users/css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'users/assets/favicon.ico' %}"/>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>

        <div class="container">

            <div class="header__menu">
                <div class="header__inner">
                    <a href="{% url 'index' %}"><img src="{% static 'users/assets/logo.png' %}" width="62px" height="60px" alt="site logo"></a>
                    <span class="header__title">Социально Новостной Сайт</span>

                </div>

                <div class="header__nav">

                    {% if user.is_authenticated %}

                    <div class="header__nav__link">
                        <a href="{% url 'create' %}" class="btn" style="margin-right: 20px;">Создать тему</a>
                    </div>

                    <div class="header__nav__link">
                        <a class="header__nav__nick" href="{% url 'profile' %}">{{ user.username }}</a> |
                    </div>
                    <div class="header__nav__link">
                        <form method="POST" action="{% url 'logout' %}">
                            {% csrf_token %}
                            <button type="submit" class="btn">Выйти</button>
                        </form>
                    </div>

                    {% else %}                        
                        <div class="header__nav__link">
                            <div class="btn signin">Войти</div>
                        </div>
                        <div class="header__nav__link">
                            <div class="btn signup">Зарегистрироваться</div>
                        </div>
                    {% endif %}

                </div>
            </div>

        </div> <!-- /.container -->
    </header>

    <div class="modal__signup">

        <div class="modal__content">
            <div class="modal__signup__close">x</div>
            <div class="modal__title">Регистрация</div>
            <div class="modal__errors"></div>

            <form id="register__form" method="POST" action="{% url 'register' %}">
                {% for f in RegisterForm %}
                    <div class="inner__form">
                        <p>{{ f }}</p>
                        <label class="form__error {{ f.name }}"></label>
                    </div>
                {% endfor %}
                {% csrf_token %}
                <button class="btn" type="submit">Зарегистрироваться</button>
            </form>
        </div>
        
    </div> <!-- /.modal__signup --> 

    <div class="modal__signin">

            <form action="{% url 'login' %}" class="modal__content" id="login__form" method="POST">
                <div class="modal__signin__close">x</div>
                <div class="modal__title">Авторизация</div>
                <div class="modal__errors"></div>
                {% for f in LoginForm %}
                    <div class="inner__form">
                        <p>{{ f }}</p>
                        <label class="form__error {{ f.name }}"></label>
                    </div>
                    <label class="form__error {{ f.name }}"></label>
                {% endfor %}

                {% csrf_token %}
                <button class="btn" type="submit">Войти</button>
            </form>
        
    </div> <!-- /.modal__signin --> 


        {% block content %}{% endblock %}

    <script src="{% static 'users/scripts/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'users/scripts/main.js' %}"></script>
    <script src="{% static 'users/scripts/run_prettify.js' %}"></script>
</body>
</html>

social_news_site/users/templates/users/index.html
{% extends "users/base.html" %}

{% block title %}{{ title }}{% endblock %}


{% block content %}

<div class="content">

    <div class="container">
        <div class="content__title">Поиск на сайте</div>
            <form class="content__inner" method="POST">
                {% csrf_token %}
                <input name="search" type="search" class="content__search">
                <button class="btn">Поиск</button>
            </form>

        <div class="content__search__category">
            <div class="content__search__title">Искать по категории</div>
            <div class="content__category__line">

                {% for c in categories %}
                    <a class="content__search__item" href="{% url 'search' %}?cat={{ c.pk }}">{{ c.name }}</a>
                {% endfor %}
                
            </div>

        </div>

    </div>
</div>
{% endblock %}

social_news_site/users/templates/users/profile.html
{% extends "users/base.html" %}
{% load spurl %}

{% block title %}{{ title }}{% endblock %}


{% block content %}



<div class="content">

    <div class="container">
        
        <div class="profile">
        
            <div class="profile__change__photo">
                {% if user.photo %}
                    <img class="profile__photo" src="{{ user.photo.url }}">
                {%  else %}
                <img class="profile__photo" src="{{ default_photo }}">
                {% endif %}
                <form id="change_photo" enctype="multipart/form-data" method="POST">
                    {% csrf_token %}
                    <input type="file" name="photo" id="id_photo" hidden>
                    <button class="btn profile__change__photo__button">Изменить фото</button>
                </form>
            </div>
        
            <div class="profile__data">
                <div class="profile__nick">Логин: {{ user.username }}</div>
                <div class="profile__register">Регистрация: {{ user.date_joined|date:"Y-m-d" }}</div>
                <div class="profile__lastEntry">Последний раз заходил(а): {{ user.last_login|date:"Y-m-d" }}</div>
                <div>Количество сообщений: {{ user.message_count }}</div>
                </form>   
            </div>
        </div> <!-- /.profile -->
        
        <div class="profile__themes">
            <div class="profile__title">Мой темы</div>

            
            
            <div style="text-align: center;">

                {% if themes.has_other_pages %}

                    {% if themes.has_previous %}
                        <a href="{% spurl path=request.get_full_path query=request.GET set_query='page={{ themes.previous_page_number }}' %}" class="btn">&lt;</a>
                    {% endif %}

                    {% for p in themes.paginator.page_range %}
                        {% if themes.number == p %}
                            <a class="btn" style="background-color: #ccc;" href="?page={{ p }}">{{ p }}</a>
                        {% elif p >= themes.number|add:-2 and p <= themes.number|add:2 %}
                        <a class="btn" href="?page={{ p }}">{{ p }}</a>
                        {% endif %}
                        
                    {% endfor %}

                    {% if themes.has_next %}
                        <a href="{% spurl path=request.get_full_path query=request.GET set_query='page={{ themes.next_page_number }}' %}" class="btn">&gt;</a>
                    {% endif %}
                {% endif %}

            </div>

            <div class="search__results">

                {% if themes %}
                    {% for article in themes %}

                        <div class="theme">

                            <div class="theme__info">
                                <div>{{ article.time_create|date:"Y-m-d" }}</div>
                                <div>Количество ответов: {{ article.count }}</div>
                            </div>

                            <div class="theme__content">
                                {{ article.title|truncatechars:60 }}
                                <a href="{{ article.get_absolute_url }}" class="btn">открыть</a>

                            </div>
                        </div>

                    {% endfor %}
                {% else %}
                        <div style="margin-top: 70px; font-size: 23px; text-align: center;">Отсутствуют</div>
                {% endif %}

            </div>

        </div>

    </div> <!-- /.container -->
</div> <!-- /.content -->

{% endblock %}

social_news_site/users/templates/users/register_done.html
{% extends "users/base.html" %}

{% block title %}{{ title }}{% endblock %}


{% block content %}

<div class="content">

    <div class="container">
        
        <h3 style="text-align: center;">Вы успешно зарегистрировались на сайте. Перейти на <a href="{% url 'index' %}">главную страницу</a></h3>

    </div>
</div>
{% endblock %}